### ISSUE TITLE
Licensing is unclear

### ISSUE THREAD

**Issue by lukelane124** [Malvineous/cfgpath#8]
I really love this project, however, I am unable to incorporate it's wondrous abilities into our programs due to the licensing not being defined on this platform. 
This stackoverflow answer mentioned it's public domain, but I can't verify the authenticity of that claim.

https://stackoverflow.com/a/18418391

Please update your license definition to match how you wish this code to be treated.
Thanks!!!!!

**Comment by Malvineous** [comment]
Resolved in e61ad5fc3877d6d2ad2508822fb3549720fa0313, thanks!

**Comment by Malvineous** [comment]
BTW it does say in the Readme it's public domain too :)
